// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.9
// source: async_messaging/publisher_service.proto

package asyncMessaging

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AsyncMessagingPublisherService_PublishMessage_FullMethodName = "/accelbyte.extend.async_messaging.AsyncMessagingPublisherService/PublishMessage"
)

// AsyncMessagingPublisherServiceClient is the client API for AsyncMessagingPublisherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AsyncMessagingPublisherServiceClient interface {
	PublishMessage(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type asyncMessagingPublisherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAsyncMessagingPublisherServiceClient(cc grpc.ClientConnInterface) AsyncMessagingPublisherServiceClient {
	return &asyncMessagingPublisherServiceClient{cc}
}

func (c *asyncMessagingPublisherServiceClient) PublishMessage(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AsyncMessagingPublisherService_PublishMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsyncMessagingPublisherServiceServer is the server API for AsyncMessagingPublisherService service.
// All implementations must embed UnimplementedAsyncMessagingPublisherServiceServer
// for forward compatibility
type AsyncMessagingPublisherServiceServer interface {
	PublishMessage(context.Context, *PublishMessageRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAsyncMessagingPublisherServiceServer()
}

// UnimplementedAsyncMessagingPublisherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAsyncMessagingPublisherServiceServer struct {
}

func (UnimplementedAsyncMessagingPublisherServiceServer) PublishMessage(context.Context, *PublishMessageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishMessage not implemented")
}
func (UnimplementedAsyncMessagingPublisherServiceServer) mustEmbedUnimplementedAsyncMessagingPublisherServiceServer() {
}

// UnsafeAsyncMessagingPublisherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AsyncMessagingPublisherServiceServer will
// result in compilation errors.
type UnsafeAsyncMessagingPublisherServiceServer interface {
	mustEmbedUnimplementedAsyncMessagingPublisherServiceServer()
}

func RegisterAsyncMessagingPublisherServiceServer(s grpc.ServiceRegistrar, srv AsyncMessagingPublisherServiceServer) {
	s.RegisterService(&AsyncMessagingPublisherService_ServiceDesc, srv)
}

func _AsyncMessagingPublisherService_PublishMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncMessagingPublisherServiceServer).PublishMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncMessagingPublisherService_PublishMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncMessagingPublisherServiceServer).PublishMessage(ctx, req.(*PublishMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AsyncMessagingPublisherService_ServiceDesc is the grpc.ServiceDesc for AsyncMessagingPublisherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AsyncMessagingPublisherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.extend.async_messaging.AsyncMessagingPublisherService",
	HandlerType: (*AsyncMessagingPublisherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishMessage",
			Handler:    _AsyncMessagingPublisherService_PublishMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "async_messaging/publisher_service.proto",
}
